sudo: required

dist: trusty

language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libtool intltool autoconf automake libcurl4-openssl-dev
  - sudo apt-get install -y pkg-config libglib2.0-dev libgtk-3-dev libgoocanvas-2.0-dev

script:
  - ./autogen.sh
  - make

